//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTitle
    {
        public JobTitle()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int JobTitle_id { get; set; }
        public string JobTitle1 { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
