//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Registartion_id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string LastName { get; set; }
        public string Logins { get; set; }
        public string Passwords { get; set; }
        public Nullable<System.DateTime> BlockedUtil { get; set; }
        public Nullable<int> JobTitle_id { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
    }
}
